stages:
  - test
  - build
  - deploy

variables:
  BACKEND_IMAGE: "$CI_REGISTRY_IMAGE/backend"
  FRONTEND_IMAGE: "$CI_REGISTRY_IMAGE/frontend"

test-backend:
  stage: test
  image: python:3.11
  script:
    - cd backend
    - pip install --quiet -r requirements.txt
    - pytest tests/ -v --tb=short || echo "No tests found"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

build-backend:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$BACKEND_IMAGE:$CI_COMMIT_SHA" -t "$BACKEND_IMAGE:latest" ./backend
    - docker push "$BACKEND_IMAGE:$CI_COMMIT_SHA"
    - docker push "$BACKEND_IMAGE:latest"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

build-frontend:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$FRONTEND_IMAGE:$CI_COMMIT_SHA" -t "$FRONTEND_IMAGE:latest" ./frontend
    - docker push "$FRONTEND_IMAGE:$CI_COMMIT_SHA"
    - docker push "$FRONTEND_IMAGE:latest"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

update-helm-values:
  stage: deploy
  tags:
    - wsl2-local-runner
  script:
    - git config user.email ci@gitlab.com
    - git config user.name GitLabCI
    - sed -i "s/tag:.*/tag: $CI_COMMIT_SHA/" helm/values.yaml
    - git add helm/values.yaml
    - git diff --cached --quiet && echo no-changes || git commit -m ci-update-tags
    - git remote set-url origin https://amenimnasri8:$GITLAB_TOKEN@gitlab.com/amenimnasri8/Finops-platform.git
    - git push origin HEAD:main
  needs:
    - build-backend
    - build-frontend
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'