apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend-sa
      imagePullSecrets:
        - name: {{ index .Values.imagePullSecrets 0 "name" }}

      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.port }}
              name: http

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds:       10
            timeoutSeconds:       5
            failureThreshold:     3

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 15
            periodSeconds:       15
            timeoutSeconds:       5
            failureThreshold:     3

          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
