apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port:       {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      protocol:   TCP
      name:       postgres
  selector:
    app: postgres
