apiVersion: v1
kind: Secret
metadata:
  name: finops-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: finops-platform
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres-service.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"
  SECRET_KEY:   {{ .Values.secrets.secretKey  | quote }}
  JWT_SECRET:   {{ .Values.secrets.jwtSecret  | quote }}
