apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port:       {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol:   TCP
      name:       http
  selector:
    app: backend
